* ====================================================================
* Supplementary script: Generate standardized mechanism tables
* ====================================================================
* This script generates 24 additional standardized table versions
* from the coefficients stored after running 04_mechanisms_enigh_1998_2000_all.do
*
* Uses coefficient transformations:
* - Z-score: coeff × SD(intensity)
* - Percentage: (coeff × mean(intensity) / mean(outcome)) × 100
* - Marginal: coeff × mean(intensity)
*
* Run this AFTER completing 04_mechanisms_enigh_1998_2000_all.do
* ====================================================================

* NOTE: Adjust table output path as needed
* global tables "C:\Users\FELIPEME\Dropbox\Aplicaciones\Overleaf\progresa_cct\tables"

* ====================================================================
* 1998 INTENSITY - STANDARDIZED TABLES
* ====================================================================

* T1_IND_ZSCORE, T1_IND_PCT, T1_IND_MARG (already generated by main script)
* T2_HH_ZSCORE
* T3_FOOD_ZSCORE
* T4_HEALTH_ZSCORE
* T2_HH_PCT, T3_FOOD_PCT, T4_HEALTH_PCT
* T2_HH_MARG, T3_FOOD_MARG, T4_HEALTH_MARG

* INSTRUCTION: After running the main script (04_mechanisms_enigh_1998_2000_all.do):
*
* 1. The coefficient macros for 1998 individual outcomes are computed:
*    OLS_w98_z_1 through OLS_w98_z_7 (z-score versions)
*    OLS_w98_pct_1 through OLS_w98_pct_7 (percentage versions)
*    OLS_w98_marg_1 through OLS_w98_marg_7 (marginal versions)
*    (and f98 and m98 variants for female and male)
*
* 2. For HOUSEHOLD, FOOD, and HEALTH tables (T2, T3, T4):
*    You need to add the coefficient transformation logic to 04_mechanisms_enigh_1998_2000_all.do
*    following the same pattern as the individual outcomes loop (lines ~265-405)
*
* 3. Once those macros are generated, this script can create the table output.
*    For now, use the template below as a reference for generating remaining tables.

* ====================================================================
* TEMPLATE: T2_HH_ZSCORE for 1998
* ====================================================================
* Uncomment and customize when household outcome macros are available:

/*
{
	cap file close sm
	file open sm using "$tables/1998/T2_hh_enigh_1992_1998_all_zscore.tex", write replace
	file write sm "\begin{tabular}{lccccccccc} \hline \hline"_n
	file write sm "& \multicolumn{1}{c}{Earnings} & \multicolumn{1}{c}{Income} & \multicolumn{1}{c}{Expenditure} & \multicolumn{1}{c}{Progresa} & \multicolumn{1}{c}{Transfers} & \multicolumn{1}{c}{Savings} & \multicolumn{1}{c}{Debt} & \multicolumn{1}{c}{N HH}   \\ "_n
	file write sm "\cmidrule(lr){2-2}\cmidrule(lr){3-3}\cmidrule(lr){4-4} \cmidrule(lr){5-5}\cmidrule(lr){6-6}\cmidrule(lr){7-7}\cmidrule(lr){8-8}\cmidrule(lr){9-9}"_n
	file write sm "& (1) & (2) & (3) & (4) & (5) & (6) & (7) & (8) \\  \toprule"_n
	file write sm "\underline{\textit{Panel A: Pooled}}  \\  "_n
	file write sm "\textit{Intensity 1998 x post (Z-score)} & `OLS_w98_z_1'  & `OLS_w98_z_2' & `OLS_w98_z_3' & `OLS_w98_z_4' & `OLS_w98_z_5' & `OLS_w98_z_6' & `OLS_w98_z_7' & `OLS_w98_z_8'\\  "_n
	file write sm "& (`SE_w98_1')  & (`SE_w98_2') & (`SE_w98_3') & (`SE_w98_4') & (`SE_w98_5')  & (`SE_w98_6') & (`SE_w98_7') & (`SE_w98_8')\\ "_n
	file write sm "  & & &  & & & &  & \\ "_n
	file write sm "Mean (1992-1996) & `mean_dep_w1'  & `mean_dep_w2' & `mean_dep_w3' & `mean_dep_w4' & `mean_dep_w5' & `mean_dep_w6'& `mean_dep_w7' & `mean_dep_w8'  \\  "_n
	file write sm "Avg Intensity & `inten1998_mean_str'  & `inten1998_mean_str' & `inten1998_mean_str' & `inten1998_mean_str' & `inten1998_mean_str' & `inten1998_mean_str'& `inten1998_mean_str' & `inten1998_mean_str'  \\  "_n
	file write sm "Obs & `N_w1'  & `N_w2' & `N_w3' & `N_w4' & `N_w5' & `N_w6' & `N_w7' & `N_w8' \\ "_n
	file write sm "  & & &  & & & &  & \\ "_n
	file write sm "\underline{\textit{Panel B: Females}}  \\  "_n
	* [Repeat for females with f98 macros]
	* [Repeat for males with m98 macros]
	file write sm "No. Mun & `n_mun1'  & `n_mun2' & `n_mun3' & `n_mun4' & `n_mun5' & `n_mun6' & `n_mun7' & `n_mun8' \\  "_n
	file write sm "Year FE & Y & Y & Y & Y & Y & Y & Y & Y  \\ "_n
	file write sm "Mun FE & Y & Y & Y & Y & Y & Y & Y & Y \\ "_n
	file write sm "Mun Controls & N  & N & N & N & N  & N & N & N     \\  "_n
	file write sm "Cluster SE: Mun & Y & Y & Y & Y & Y & Y & Y & Y  \\ "_n
	file write sm "Note: Coefficients show effect per 1 SD increase in intensity \\ "_n
	file write sm "\bottomrule"_n
	file write sm "\end{tabular}"
	file close sm
}
*/

* ====================================================================
* INSTRUCTIONS FOR COMPLETING ALL 24 TABLES
* ====================================================================
*
* Step 1: Modify 04_mechanisms_enigh_1998_2000_all.do to compute
*         coefficient transformations for household (T2), food (T3),
*         and health (T4) outcomes, following the pattern from
*         individual outcomes (lines ~265-405).
*
* Step 2: Add table output sections for each standardized version.
*         You can copy-paste the T1_IND_ZSCORE/PCT/MARG table code
*         and adapt column names and macro references.
*
* Step 3: Repeat for 2000 intensity (inten2000) across all 4 outcomes.
*
* Required modifications to main script for EACH outcome set (T2, T3, T4):
*
* A. In regression loops, compute:
*    - coef_raw = _b[...coefficient...]
*    - coef_zscore = coef_raw * SD_intensity
*    - coef_pct = (coef_raw * mean_intensity / mean_outcome) * 100
*    - coef_marg = coef_raw * mean_intensity
*
* B. Format and store in macros (w98_z, w98_pct, w98_marg, etc.)
*
* C. Create 3 new table sections for each outcome set
*    (zscore, pct, marg versions)
*
* D. Repeat for 2000 intensity using inten2000 and w00 macro prefixes

